global class DJ_DoctorWrapper {

    public String Id { get; set; }

    public String firstName { get; set; }
    public String lastName { get; set; }
    public String specialty { get; set; }
    public String nationality { get; set; }
    public String startOfCareer { get; set; }
    public String dateOfBirth { get; set; }
    public String phone { get; set; }
    public String country  { get; set; }
    public String city { get; set; }
    public String street { get; set; }
    public String postalCode { get; set; }
    public String licenseNumber { get; set; }

    public String email { get; set; }

    public String backMessage { get; set; }
    public Boolean selected { get; set; }
    
}